#!/usr/bin/env node

// yargs command module code, see https://github.com/yargs/yargs/blob/main/docs/advanced.md#example-command-hierarchy-using-commanddir
const argv = require('yargs/yargs')(process.argv.slice(2))
  .commandDir('cmds')
  .demandCommand(1, 'You need at least one command before moving on')
  .env('WAM_IMAGE_CLASSIFIER')
// Global options for all scripts
  .option('cache-folder', {
    alias: 'cf',
    description: 'Cache Folder path',
    hidden: true,
    default: './.cache'
  })
  .option('debug', {
    alias: 'd',
    description: 'Output debug information to stdout',
    type: 'boolean',
    default: false
  })
  .option('force', {
    alias: 'f',
    description: 'Ignore local cache and force classification',
    type: 'boolean',
    default: false
  })
  .option('key', {
    description: 'Name of the google API key file placed in the keys folder. See https://cloud.google.com/docs/authentication/getting-started to get the JSON key file.',
    default: 'google.json',
  })
  .option('verbose', {
    alias: 'v',
    description: 'Verbose output',
    default: false,
    type: 'boolean'
  })
  .wrap(null)
  .help()
  .argv